# API Costs
api_costs:
  whisper:
    cost_per_minute: 0.006  # USD per minute for Whisper
  pyannote:
    cost_per_hour: 0.18     # USD per hour for diarization

# Logging Configuration
logging:
  log_directory: "logs"
  max_log_size: 10485760      # 10 MB in bytes
  backup_count: 5

# Model Configuration
model:
  default_model_id: "openai/whisper-large-v3"

# Supported Services
supported_upload_services:
  - "0x0.st"
  - "file.io"

# Timeout Settings (in seconds)
timeouts:
  download_timeout: 60  # {{ edit: Add download_timeout with a default value of 60 seconds }}
  upload_timeout: 120    # {{ edit: Ensure upload_timeout is defined }}
  diarization_timeout: 3600
  job_status_timeout: 60

# Transcription Settings
transcription:
  generate_timeout: 300  # Timeout for transcription in seconds
  max_target_positions: 448
  buffer_tokens: 10  # Reduced from 445 to 10

# API Tokens
# pyannote_token: "your_pyannote_api_token_here"
# openai_key: "your_openai_api_key_here"