name: Generate Requirements

on:
  push:
    branches:
      - main  # Adjust if you have a different default branch
    paths:
      - 'pyproject.toml'
      - 'poetry.lock'

jobs:
  update-requirements:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Allows pushing changes to the repository

    steps:
      - name: Check out repository
        uses: actions/checkout@v3  # Update to @v4 if available

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.4'

    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry

    - name: Configure Poetry
      run: |
        poetry config virtualenvs.create false

    - name: Regenerate requirements.txt
      run: |
        poetry lock
        poetry export -f requirements.txt --output requirements.txt --without-hashes

      - name: Upload requirements.txt as artifact
        uses: actions/upload-artifact@v4
        with:
          name: requirements
          path: requirements.txt
