name: Generate Requirements

on:
  push:
    paths:
      - 'pyproject.toml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Generate requirements.txt
        run: poetry export -f requirements.txt --output requirements.txt --without-hashes

      - name: Upload requirements.txt as artifact
        uses: actions/upload-artifact@v3
        with:
          name: requirements
          path: requirements.txt
